package it.regoladelgiorno.core

/** GENERATO da regole.py: specchio del contenuto di assets/regole.json. */
val CATALOGO_REALE: List<Regola> = listOf(
    Regola("soc-01", "Oggi ringrazia qualcuno per una cosa che ha fatto più di un anno fa.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-02", "Oggi fai una domanda in più a chi vedi ogni giorno.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("soc-03", "Oggi complimenta uno sconosciuto per qualcosa che ha scelto lui.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("soc-04", "Oggi fai tu il primo passo con chi stavi per evitare.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("soc-05", "Oggi chiedi a qualcuno che lavoro facevano i suoi genitori.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-06", "Oggi telefona a una persona a cui pensi e non senti.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-07", "Oggi lascia parlare l'altro fino in fondo, senza completare le frasi.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-08", "Oggi presenta fra loro due persone che non si conoscono.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("soc-09", "Oggi di' di no a una cosa che avresti accettato per inerzia.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("soc-10", "Oggi chiedi scusa per una cosa piccola che nessuno ha notato.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-11", "Oggi mangia in compagnia, non per conto tuo.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("soc-12", "Oggi saluta per nome chi di solito saluti e basta.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("soc-13", "Oggi racconta a qualcuno una cosa che di solito ti tieni.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("soc-14", "Oggi ascolta una storia già sentita senza dire che la conosci.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-15", "Oggi chiedi un consiglio a chi non lo chiederesti mai.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("soc-16", "Oggi fai una domanda che rischia di avere una risposta lunga.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-17", "Oggi offri aiuto prima che qualcuno lo chieda.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-18", "Oggi riprendi una conversazione lasciata a metà settimane fa.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-19", "Oggi scambia due parole con chi ti serve al banco.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("soc-20", "Oggi scrivi a mano un biglietto e consegnalo di persona.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-21", "Oggi accetta il primo invito che ricevi.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-22", "Oggi chiedi a un collega su cosa sta lavorando davvero.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.FERIALE, 2, cooldownGiorni = 60),
    Regola("soc-23", "Oggi resta cinque minuti in più dopo i saluti.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("soc-24", "Oggi di' a qualcuno una cosa che apprezzi e non hai mai detto.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("soc-25", "Oggi chiedi come sta e aspetta la seconda risposta.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("soc-26", "Oggi difendi un'opinione che di solito tieni per te.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("soc-27", "Oggi vai a trovare qualcuno che non vedi da tempo.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.FESTIVO, 3, cooldownGiorni = 60),
    Regola("soc-28", "Oggi cedi il turno a chi hai dietro.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("soc-29", "Oggi chiedi a qualcuno di insegnarti una cosa che sa fare.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("soc-30", "Oggi siediti accanto a qualcuno invece che di fronte.", Categoria.SOCIALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("fis-01", "Oggi cammina venti minuti senza destinazione. Non è un tragitto.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 2, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 2000, cooldownGiorni = 60),
    Regola("fis-02", "Oggi scendi una fermata prima e fai il resto a piedi.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.FERIALE, 1, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 1200, cooldownGiorni = 60),
    Regola("fis-03", "Oggi fai le scale ogni volta che puoi scegliere.", Categoria.FISICO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("fis-04", "Oggi allunga di dieci minuti la strada verso casa.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 1, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 1000, cooldownGiorni = 60),
    Regola("fis-05", "Oggi cammina mentre parli al telefono.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 1, metrica = Metrica.PASSI_SOPRA_BASELINE_PERCENTUALE, soglia = 10, cooldownGiorni = 60),
    Regola("fis-06", "Oggi fai il giro dell'isolato prima di entrare.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 1, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 600, cooldownGiorni = 60),
    Regola("fis-07", "Oggi vai a piedi dove andresti in macchina.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 2, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 1500, cooldownGiorni = 60),
    Regola("fis-08", "Oggi esci di casa entro un'ora dal risveglio.", Categoria.FISICO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("fis-09", "Oggi cammina dopo cena, anche solo dieci minuti.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 1, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 800, cooldownGiorni = 60),
    Regola("fis-10", "Oggi porta a piedi una cosa che avresti spedito.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 2, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 1000, cooldownGiorni = 60),
    Regola("fis-11", "Oggi fai la spesa a piedi.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 2, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 1200, cooldownGiorni = 60),
    Regola("fis-12", "Oggi cambia strada per andare dove vai sempre.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 1, metrica = Metrica.PASSI_SOPRA_BASELINE_PERCENTUALE, soglia = 5, cooldownGiorni = 60),
    Regola("fis-13", "Oggi resta in piedi durante una telefonata lunga.", Categoria.FISICO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("fis-14", "Oggi stiracchiati ogni volta che ti accorgi di non muoverti da un po'.", Categoria.FISICO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("fis-15", "Oggi cammina dieci minuti prima di decidere una cosa.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 2, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 800, cooldownGiorni = 60),
    Regola("fis-16", "Oggi arriva a piedi in un posto che non conosci.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.FESTIVO, 3, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 1500, cooldownGiorni = 60),
    Regola("fis-17", "Oggi percorri un chilometro in più del solito.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 2, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 1300, cooldownGiorni = 60),
    Regola("fis-18", "Oggi sali le scale invece di aspettare l'ascensore.", Categoria.FISICO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("fis-19", "Oggi porta fuori la spazzatura per la strada più lunga.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 1, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 400, cooldownGiorni = 60),
    Regola("fis-20", "Oggi accompagna qualcuno a piedi invece di salutarlo sulla porta.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 2, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 700, cooldownGiorni = 60),
    Regola("fis-21", "Oggi cammina con le mani fuori dalle tasche.", Categoria.FISICO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("fis-22", "Oggi raddoppia i passi che fai di solito.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 3, metrica = Metrica.PASSI_SOPRA_BASELINE_PERCENTUALE, soglia = 100, cooldownGiorni = 60),
    Regola("fis-23", "Oggi esci a camminare anche se piove.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 3, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 1000, cooldownGiorni = 60),
    Regola("fis-24", "Oggi fai una pausa in piedi ogni ora.", Categoria.FISICO, Livello.DICHIARATA, Contesto.FERIALE, 1, cooldownGiorni = 60),
    Regola("fis-25", "Oggi corri per cento metri, una volta sola.", Categoria.FISICO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("fis-26", "Oggi cammina fino a vedere qualcosa che non avevi mai visto.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.FESTIVO, 3, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 1500, cooldownGiorni = 60),
    Regola("fis-27", "Oggi lascia l'auto e vai in bicicletta.", Categoria.FISICO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("fis-28", "Oggi cammina piano, più piano del solito.", Categoria.FISICO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("fis-29", "Oggi esci a camminare prima di colazione.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 2, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 600, cooldownGiorni = 60),
    Regola("fis-30", "Oggi torna a casa dalla strada più lunga.", Categoria.FISICO, Livello.OSSERVABILE, Contesto.QUALSIASI, 1, metrica = Metrica.PASSI_SOPRA_BASELINE_ASSOLUTI, soglia = 900, cooldownGiorni = 60),
    Regola("dig-01", "Oggi telefona a chi avresti scritto.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-02", "Oggi tieni il telefono in un'altra stanza mentre mangi.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("dig-03", "Oggi non aprire i social prima di mezzogiorno.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-04", "Oggi rispondi a un messaggio solo quando puoi dedicargli attenzione.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-05", "Oggi esci senza cuffie.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-06", "Oggi lascia il telefono in borsa mentre cammini.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("dig-07", "Oggi guarda una cosa sola alla volta, senza secondo schermo.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-08", "Oggi cancella un'applicazione che apri per abitudine.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("dig-09", "Oggi non fotografare niente.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-10", "Oggi metti il telefono in bianco e nero.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-11", "Oggi leggi su carta qualcosa che avresti letto sullo schermo.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("dig-12", "Oggi rispondi alle email in un unico momento.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.FERIALE, 2, cooldownGiorni = 60),
    Regola("dig-13", "Oggi non controllare le notifiche finché non ti fermi.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-14", "Oggi spegni il telefono per un'ora, e avvisa prima qualcuno.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("dig-15", "Oggi cerca una cosa senza chiedere a internet.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-16", "Oggi non usare la navigazione satellitare.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-17", "Oggi scrivi un messaggio lungo invece di cinque corti.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("dig-18", "Oggi togli il telefono dal tavolo quando parli con qualcuno.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("dig-19", "Oggi ascolta un disco intero, nell'ordine in cui è fatto.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("dig-20", "Oggi non guardare video mentre fai altro.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-21", "Oggi lascia il telefono a caricare lontano dal letto.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-22", "Oggi rispondi a voce invece che a messaggio.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("dig-23", "Oggi disattiva le notifiche di una sola applicazione.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("dig-24", "Oggi non leggere i commenti.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("dig-25", "Oggi guarda l'orologio solo quando serve davvero.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-26", "Oggi chiudi tutte le schede aperte e ricomincia.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.FERIALE, 1, cooldownGiorni = 60),
    Regola("dig-27", "Oggi non mettere segni di approvazione a nessuno.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-28", "Oggi scrivi a qualcuno senza aspettarti risposta.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("dig-29", "Oggi tieni lo schermo al minimo della luminosità.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("dig-30", "Oggi finisci un articolo prima di aprirne un altro.", Categoria.DIGITALE, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-01", "Oggi scrivi a mano qualcosa che avresti digitato.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-02", "Oggi fotografa una cosa sola, e nient'altro.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-03", "Oggi disegna male un oggetto che hai davanti.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-04", "Oggi inventa un nome per una cosa che non ce l'ha.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-05", "Oggi cucina senza ricetta.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-06", "Oggi scrivi tre righe su come è cominciata la giornata.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-07", "Oggi canta qualcosa ad alta voce, senza nessuno intorno.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-08", "Oggi sposta un mobile.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-09", "Oggi ascolta un genere di musica che non ascolti mai.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-10", "Oggi scrivi la fine di una storia che non hai iniziato.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-11", "Oggi fai una cosa con la mano sbagliata.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-12", "Oggi impara a dire una frase in una lingua che non parli.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-13", "Oggi costruisci qualcosa con quello che stavi per buttare.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-14", "Oggi scrivi una lista di cose che non farai mai.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-15", "Oggi cambia il modo di fare una cosa che fai in automatico.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-16", "Oggi leggi ad alta voce una pagina a qualcuno.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-17", "Oggi metti un fiore o una foglia da qualche parte in casa.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-18", "Oggi prova una ricetta di un posto che non hai mai visitato.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.FESTIVO, 2, cooldownGiorni = 60),
    Regola("cre-19", "Oggi disegna la pianta della casa della tua infanzia.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-20", "Oggi scrivi un titolo per la giornata di ieri.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-21", "Oggi indossa una cosa che tieni per le occasioni.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-22", "Oggi rimetti in funzione un oggetto rotto.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("cre-23", "Oggi leggi una poesia. Una sola, due volte.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-24", "Oggi cambia una regola di casa tua per un giorno.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-25", "Oggi apri un libro a caso e leggi una pagina.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-26", "Oggi fai una fotografia di una cosa brutta.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-27", "Oggi scrivi il primo ricordo che ti viene, senza sceglierlo.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("cre-28", "Oggi prepara da mangiare per qualcun altro.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.FESTIVO, 2, cooldownGiorni = 60),
    Regola("cre-29", "Oggi cambia posto alla sedia dove ti siedi sempre.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("cre-30", "Oggi finisci una cosa che avevi lasciato a metà.", Categoria.CREATIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-01", "Oggi non guardare l'ora fino a mezzogiorno.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-02", "Oggi nota chi parla di più nelle conversazioni a cui partecipi.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-03", "Oggi accorgiti di quando stai per dire una bugia piccola.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-04", "Oggi conta quante volte ti scusi senza motivo.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-05", "Oggi resta dieci minuti senza fare niente.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-06", "Oggi scrivi cosa ti ha dato fastidio, e perché.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-07", "Oggi mangia un pasto senza fare altro.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-08", "Oggi nota la prima cosa che pensi al risveglio.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-09", "Oggi chiediti, una volta, se quello che stai facendo lo fai per te.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("int-10", "Oggi accorgiti di quale mano usi per prima.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-11", "Oggi osserva per un minuto una persona che non conosci.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-12", "Oggi nota il momento in cui ti stanchi.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-13", "Oggi non dare consigli a nessuno.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("int-14", "Oggi accorgiti di quando cambi argomento.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-15", "Oggi guarda fuori dalla finestra per cinque minuti.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-16", "Oggi nota la prima cosa che ti fa sorridere.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-17", "Oggi resta in silenzio per la prima ora della giornata.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.FESTIVO, 3, cooldownGiorni = 60),
    Regola("int-18", "Oggi chiediti cosa avresti fatto a vent'anni.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-19", "Oggi nota quante volte controlli se hai ragione.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-20", "Oggi ascolta i suoni della casa prima di accendere qualcosa.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-21", "Oggi scrivi una cosa su cui hai cambiato idea.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-22", "Oggi accorgiti di quando smetti di ascoltare.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-23", "Oggi nota di cosa hai paura senza motivo.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-24", "Oggi conta le cose che possiedi in una stanza sola.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-25", "Oggi chiediti chi ti manca, senza andare oltre.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
    Regola("int-26", "Oggi nota quante decisioni prendi prima delle nove.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-27", "Oggi ritarda di dieci minuti il sonno, al buio, senza schermi.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-28", "Oggi accorgiti di quale rumore ti dà più fastidio.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 1, cooldownGiorni = 60),
    Regola("int-29", "Oggi nota cosa fai quando nessuno ti guarda.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 2, cooldownGiorni = 60),
    Regola("int-30", "Oggi chiediti se questa giornata ti somiglia.", Categoria.INTROSPETTIVO, Livello.DICHIARATA, Contesto.QUALSIASI, 3, cooldownGiorni = 60),
)
